import React from 'react';
import styled from 'styled-components';

import background from '../../assets/background_one.png';
import presets from '../presets';
import { Title, Text, PreText, SubText, SubTitle } from './styles/TextStyles';
import { NavigationButton } from './styles/ButtonStyles';
import { connect } from 'react-redux';
import { maths_api_request, CATEGORIES, QUESTIONS } from '../../redux/actions/MathsAPIAction';

class Home extends React.Component {
    constructor(props) {
        super();
        this.maths_api_category_url = 'https://maths-generator.herokuapp.com/maths/year4/categories?pretty';
    }

    componentDidMount() {
        this.props.maths_api_request(this.maths_api_category_url, CATEGORIES);
    }

    componentDidUpdate() {
        console.log(this.props.categories, this.props.questions);
    }

    call_api(api) {
        this.props.maths_api_request(api, QUESTIONS);
    }

    render() {
        return (
            <Container className="hide-scroll">
                <ContentContainer>
                    <HeaderSection>
                        <Title>Welcome to RMathematics ._</Title>
                    </HeaderSection>
                    <MainSection>
                        <SubSection>
                            <Text>
                                Studying for maths can be difficult, and when it comes to online material most students
                                will have to get by with past papers. However, while past papers are useful, there just
                                aren't enough of them. Once you complete one past paper, there really isn't a point to
                                redo it.
                            </Text>
                            <Text>
                                To maximise studying potential, this web application will randomly generate exam style
                                papers that can be fine-tuned to any level ._
                            </Text>
                            <Text>
                                This project is currently in early development. Source code is readily available on my{' '}
                                <a href={'https://github.com/KingCollege'}>github page</a> ._
                            </Text>
                        </SubSection>
                        <GridContainer>
                            <SubSection>
                                <SubTitle>User Guide ._</SubTitle>
                                <Text>
                                    Navigate to "Application" or press the button below to access the application. From
                                    there you will be given options for what type of question you want in your paper ._
                                </Text>
                                <NavigationButton>
                                    <Text>Go to Application page</Text>
                                </NavigationButton>
                                <Text>
                                    Questions are generated by an API. Below is a list of api requests, tap any of them
                                    to see what they return:
                                </Text>
                                {Object.values(this.props.categories).map((c) => {
                                    return (
                                        <Text
                                            code={true}
                                            className="select-all"
                                            key={c.api}
                                            onClick={() => this.call_api(c.api)}
                                        >
                                            {c.api}
                                        </Text>
                                    );
                                })}
                            </SubSection>
                            <SubSection>
                                <PreText>{JSON.stringify(this.props.questions, null, 2)}</PreText>
                            </SubSection>
                        </GridContainer>
                    </MainSection>
                    <FooterSection>
                        <SubText>contact: mandushi.18@gmail.com</SubText>
                    </FooterSection>
                </ContentContainer>
            </Container>
        );
    }
}

const Container = styled.div`
    position: relative;
    width: 100%;
    height: 100%;
    display: flex;
    justify-content: flex-start;
    background-color: transparent;
    background-image: url(${background});
    background-size: cover;
    background-position: center top;
    overflow: auto;
`;


const ContentContainer = styled.div`
    position: absolute;
    margin-left: 25px;
    width: 80%;
    display: flex;
    flex-direction: column;
    background-color: transparent;
`;

const GridContainer = styled.div`
    display: grid;
    width: 100%;
    grid-template-columns: 1fr 1fr;

    @media only screen and (max-width: 700px) {
        display: flex;
        flex-direction: column;
    }
`;

const HeaderSection = styled.div`
    display: flex;
    justify-content: flex-start;
    align-items: flex-end;
    border-bottom: 1px solid ${presets.color_scheme.grey};
`;

const MainSection = styled.div`
    width: 100%;
    min-height: 900px;
    display: flex;
    flex-direction: column;
    background-color: transparent;
`;

const SubSection = styled.div`
    display: flex;
    flex-direction: column;
    width: 100%;
    border-bottom: 1px solid ${presets.color_scheme.grey};
`;

const FooterSection = styled.div`
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    align-items: center;
`;

const mapStateToProps = (state) => ({
    categories: state.maths_api.categories,
    questions: state.maths_api.questions,
});

const mapDispatchToProps = (dispatch) => ({
    maths_api_request: (url, type) => dispatch(maths_api_request(url, type)),
});

export default connect(mapStateToProps, mapDispatchToProps)(Home);
